### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by timReynolds** [NextITCorp/AutoFixture.js#1]
I've used auto fixture before in c# and been looking for something similar for Javascript. Is this published as a npm package?

**Comment by JoeDumoulin** [comment]
I don't think the has been packaged up at this time. I'll verify.

**Comment by kalebpederson** [comment]
It has not. NPM does contain an autofixture project with a very different API than our version and the C# version of AutoFixture.

I looked at doing so but because of the potential name clash and a comment by Mark Seeman, the author of the C# AutoFixture. I indicated to Mark that I would be willing to work with him but I'm not sure that he saw the GitHub comment and I never followed up.

Thank you for your interest. I think it is worth packaging it up. We could potentially do autofixturejs as the package name, but the similar name might be confusing to users. Thoughts?

**Comment by timReynolds** [comment]
I found this because the API seemed to provide a nicer experience than the other project. 

If naming it similar to auto fixture causes concern I'd say stay away from it an pick something else. What's important here is this library provides something that would be useful to people if you could download it via NPM.

**Comment by kalebpederson** [comment]
Thanks Tim. The other project is on NPM as autofixture and on GitHub as autofixturejs. We'll work to get this published.

**Comment by timReynolds** [comment]
As this didn't look like it would get resolved I've created my own version published under `@timReynolds/autofixture`

This version has several enhancements based on https://github.com/timReynolds/AutoFixture.js

**Comment by NextITCorp** [comment]
Thanks for the heads-up Tim.  We got acquired about 6 months ago and haven’t kept up with this obviously.  Sorry I should have notified you earlier.

Joe D
